### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [xdid-net/webhookemail#1]
https://github.com/xdid-net/webhookemail/blob/8c584958e53a08d0b99451288bd20df9b3f75905/template.tpl#L71

When reviewing your template, we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by xdid-net** [comment]
Fixed with new version

**Comment by xdid-net** [comment]
Fixed with new version
